In [54]:
import torch
print(torch.__version__)

if torch.cuda.is_available():
  print("Running on GPU")
  print(f"System : {torch.cuda.get_device_name()}")
else:
  print("Running on CPU")

2.11.0+cu128
Running on GPU
System : Tesla T4

In [55]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

print("Libraries Successfully Loaded")

Libraries Successfully Loaded

In [56]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [57]:
df.shape

(569, 33)

In [58]:
df = df.drop(columns= ['id', 'Unnamed: 32'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   diagnosis                569 non-null    object
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  569 non-null    float64
 15  smoothness_se            569 non-null    float64
 16  compactness_se           569 non-null    float64
 17  concavity_se             569 non-null    float64
 18  concave points_se        569 non-null    float64
 19  symmetry_se              569 non-null    float64
 20  fractal_dimension_se     569 non-null    float64
 21  radius_worst             569 non-null    float64
 22  texture_worst            569 non-null    float64
 23  perimeter_worst          569 non-null    float64
 24  area_worst               569 non-null    float64
 25  smoothness_worst         569 non-null    float64
 26  compactness_worst        569 non-null    float64
 27  concavity_worst          569 non-null    float64
 28  concave points_worst     569 non-null    float64
 29  symmetry_worst           569 non-null    float64
 30  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), object(1)
memory usage: 137.9+ KB

In [59]:
X = df.iloc[:, 1:]
Y = df.iloc[:, 0]

In [60]:
## Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [61]:
df.describe()

       radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [62]:
## Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [63]:
y_train.value_counts()

diagnosis
B    288
M    167
Name: count, dtype: int64

In [64]:
## Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

## Numpy Arrays to PyTorch Tensors

In [65]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
Y_train_tensor = torch.from_numpy(y_train).reshape(-1, 1).to(torch.float64)
Y_test_tensor = torch.from_numpy(y_test).reshape(-1, 1).to(torch.float64)

In [66]:
X_train_tensor.shape

torch.Size([455, 30])

In [67]:
Y_train_tensor.shape

torch.Size([455, 1])

## Defining the Model

In [68]:
class NeuralNetwork:
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
    return loss.mean()

In [69]:
## Important Parmeters
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [72]:
model = NeuralNetwork(X_train_tensor)

for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)

    # Loss
    loss = model.loss_function(y_pred, Y_train_tensor)

    # Backward pass
    loss.backward()

    # Update parameters
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # Zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch: {epoch}, Loss: {loss.item():.4f}")

Epoch: 0, Loss: 0.5965
Epoch: 1, Loss: 0.5845
Epoch: 2, Loss: 0.5729
Epoch: 3, Loss: 0.5615
Epoch: 4, Loss: 0.5505
Epoch: 5, Loss: 0.5397
Epoch: 6, Loss: 0.5293
Epoch: 7, Loss: 0.5191
Epoch: 8, Loss: 0.5093
Epoch: 9, Loss: 0.4998
Epoch: 10, Loss: 0.4906
Epoch: 11, Loss: 0.4817
Epoch: 12, Loss: 0.4730
Epoch: 13, Loss: 0.4647
Epoch: 14, Loss: 0.4565
Epoch: 15, Loss: 0.4487
Epoch: 16, Loss: 0.4410
Epoch: 17, Loss: 0.4336
Epoch: 18, Loss: 0.4263
Epoch: 19, Loss: 0.4193
Epoch: 20, Loss: 0.4124
Epoch: 21, Loss: 0.4056
Epoch: 22, Loss: 0.3986
Epoch: 23, Loss: 0.3910
Epoch: 24, Loss: 0.3835

In [73]:
model.weights

tensor([[ 0.1352],
        [ 0.3447],
        [ 0.5052],
        [ 0.3514],
        [ 0.8317],
        [ 0.7717],
        [ 0.8414],
        [ 0.9594],
        [ 0.5772],
        [ 0.2969],
        [ 0.2506],
        [ 0.8504],
        [ 0.2228],
        [ 0.5684],
        [ 0.1256],
        [ 0.2190],
        [ 0.7709],
        [ 0.3694],
        [ 0.3313],
        [-0.0502],
        [ 0.9181],
        [ 0.4388],
        [ 1.0937],
        [ 0.9364],
        [ 0.5576],
        [ 0.8582],
        [ 0.6895],
        [ 0.4536],
        [ 0.0640],
        [ 0.7556]], dtype=torch.float64, requires_grad=True)

In [74]:
model.bias

tensor([-0.0591], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [75]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.8859649300575256