In [7]:
## Creating Model
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [15]:
## Creating model using Sequential Container
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [8]:
## Create dataset
features = torch.rand(10,5)

## Create Model
model = Model(features.shape[1])

model.forward(features=features)
# or model(features)  --> They added a magic method which is __call__.

tensor([[0.5613],
        [0.5435],
        [0.5428],
        [0.5609],
        [0.5373],
        [0.5142],
        [0.5432],
        [0.5629],
        [0.5407],
        [0.5629]], grad_fn=<SigmoidBackward0>)

In [12]:
## Show Model Weights
print(model.linear1.weight)
print(model.linear2.weight)

Parameter containing:
tensor([[-0.1919, -0.1323,  0.0196,  0.1902,  0.0876],
        [ 0.3971, -0.0713,  0.0223, -0.4312, -0.1274],
        [ 0.1573, -0.4368,  0.3064,  0.0855,  0.1578]], requires_grad=True)
Parameter containing:
tensor([[ 0.0090,  0.0895, -0.3707]], requires_grad=True)

In [13]:
print(model.linear1.bias)
print(model.linear2.bias)

Parameter containing:
tensor([-0.3001, -0.1745,  0.0296], requires_grad=True)
Parameter containing:
tensor([0.2530], requires_grad=True)

In [5]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [14]:
from torchinfo import summary
summary(model, input_size=(10, 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [16]:
## Implementing Model on a Dataset
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [18]:
df = df.drop(columns= ['id', 'Unnamed: 32'])
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [19]:
X = df.iloc[:, 1:]
Y = df.iloc[:, 0]

In [20]:
## Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [21]:
df.describe()

       radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

In [22]:
## Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
y_train.value_counts()

diagnosis
B    285
M    170
Name: count, dtype: int64

In [24]:
## Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

## Numpy Arrays to PyTorch Tensors

In [35]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

Y_train_tensor = torch.from_numpy(y_train).reshape(-1, 1).float()
Y_test_tensor = torch.from_numpy(y_test).reshape(-1, 1).float()

In [36]:
X_train_tensor.shape

torch.Size([455, 30])

In [37]:
Y_train_tensor.shape

torch.Size([455, 1])

In [45]:
class MySimpleNN(nn.Module):
  def __init__(self, features):
    super().__init__()
    self.linear = nn.Linear(features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  # def loss_function(self, y_pred, y):
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
  #   loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred))
  #   return loss.mean()

In [46]:
## Important Parmeters
learning_rate = 0.1
epochs = 25

In [47]:
loss_function = nn.BCELoss()

In [48]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    # Forward pass
    y_pred = model(X_train_tensor)

    # Loss
    loss = loss_function(y_pred, Y_train_tensor)

    # Clear Gradients
    optimizer.zero_grad()

    # Backward pass
    loss.backward()

    # Update parameters
    # with torch.no_grad():
    #     model.linear.weight -= learning_rate * model.linear.weight.grad
    #     model.linear.bias -= learning_rate * model.linear.bias.grad
    optimizer.step()

    # Zero gradients
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()

    print(f"Epoch: {epoch}, Loss: {loss.item():.4f}")

Epoch: 0, Loss: 0.4778
Epoch: 1, Loss: 0.4173
Epoch: 2, Loss: 0.3757
Epoch: 3, Loss: 0.3449
Epoch: 4, Loss: 0.3209
Epoch: 5, Loss: 0.3015
Epoch: 6, Loss: 0.2855
Epoch: 7, Loss: 0.2718
Epoch: 8, Loss: 0.2601
Epoch: 9, Loss: 0.2499
Epoch: 10, Loss: 0.2409
Epoch: 11, Loss: 0.2329
Epoch: 12, Loss: 0.2257
Epoch: 13, Loss: 0.2192
Epoch: 14, Loss: 0.2132
Epoch: 15, Loss: 0.2078
Epoch: 16, Loss: 0.2028
Epoch: 17, Loss: 0.1983
Epoch: 18, Loss: 0.1940
Epoch: 19, Loss: 0.1901
Epoch: 20, Loss: 0.1864
Epoch: 21, Loss: 0.1829
Epoch: 22, Loss: 0.1797
Epoch: 23, Loss: 0.1767
Epoch: 24, Loss: 0.1738

## Model Evaluation

In [49]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == Y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item()}")

Accuracy : 0.9649122953414917