In [1]:
## Importing Dataset
from sklearn.datasets import make_classification
import torch
import torch.nn as nn

In [2]:
# Step 1 : Create a Synthetic classification dataset using Sklearn
X, y = make_classification(
    n_samples=10,          # Number of samples
    n_features=2,          # Number of features
    n_informative=2,       # Number of informative features
    n_redundant=0,         # Number of reduntant features
    n_classes=2,           # Number of classes
    random_state=42
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
X.shape

(10, 2)

In [4]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape

(10,)

In [7]:
# Step 2 : Convert the data to Pytorch Tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [10]:
# Step 3 : Importing Datasets and Dataloaders from torch
from torch.utils.data import DataLoader, Dataset

In [11]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.lables = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.lables[index]

In [12]:
dataset = CustomDataset(features=X, labels=y)

In [13]:
len(dataset)

10

In [14]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [15]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [16]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [17]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print('-' * 50)

tensor([[ 1.7774,  1.5116],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------

## Practise

In [18]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [20]:
df = df.drop(columns= ['id', 'Unnamed: 32'])
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [21]:
X = df.iloc[:, 1:]
Y = df.iloc[:, 0]

## Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [22]:
## Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
## Encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

## Numpy Arrays to PyTorch Tensors

In [24]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()

Y_train_tensor = torch.from_numpy(y_train).reshape(-1, 1).float()
Y_test_tensor = torch.from_numpy(y_test).reshape(-1, 1).float()

In [30]:
X_train_tensor.shape

torch.Size([455, 30])

In [31]:
from torch.utils.data import Dataset, DataLoader

In [32]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [33]:
train_dataset = CustomDataset(X_train_tensor, Y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, Y_test_tensor)

In [34]:
train_dataset[10]

(tensor([-0.5639,  0.2695, -0.6164, -0.5708, -1.1425, -1.1884, -0.8023, -0.7981,
         -0.2614, -0.8671, -0.7804,  0.6387, -0.8558, -0.5895, -0.6891, -1.0709,
         -0.8398, -0.8193, -0.7243, -0.9351, -0.6107,  1.1544, -0.6789, -0.5872,
         -0.8831, -1.0434, -0.7571, -0.6107, -0.3305, -0.8519]),
 tensor([0.]))

In [35]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## Defining the Model

In [36]:
class NeuralNetwork(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [38]:
learning_rate = 0.1
epochs = 25

model = NeuralNetwork(X_train_tensor.shape[1])
loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [39]:
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    # forward pass
    y_pred = model.forward(features=batch_features)

    # loss
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameter update
    optimizer.step()

  # Loss in each epoch
  print(f'Epoch : {epoch + 1}, Loss : {loss.item()}')

Epoch : 1, Loss : 0.23406782746315002
Epoch : 2, Loss : 0.0677720159292221
Epoch : 3, Loss : 0.09843035042285919
Epoch : 4, Loss : 0.18026351928710938
Epoch : 5, Loss : 0.06900059431791306
Epoch : 6, Loss : 0.0522024966776371
Epoch : 7, Loss : 0.05454060062766075
Epoch : 8, Loss : 0.025151491165161133
Epoch : 9, Loss : 0.19746781885623932
Epoch : 10, Loss : 0.028286950662732124
Epoch : 11, Loss : 0.18603955209255219
Epoch : 12, Loss : 0.014532356522977352
Epoch : 13, Loss : 0.054405577480793
Epoch : 14, Loss : 0.0005314610316418111
Epoch : 15, Loss : 0.030886907130479813
Epoch : 16, Loss : 0.27815112471580505
Epoch : 17, Loss : 0.014379865489900112
Epoch : 18, Loss : 0.026148656383156776
Epoch : 19, Loss : 0.3429718017578125
Epoch : 20, Loss : 0.0702076181769371
Epoch : 21, Loss : 0.06768269836902618
Epoch : 22, Loss : 0.39507728815078735
Epoch : 23, Loss : 0.016454659402370453
Epoch : 24, Loss : 0.05428122729063034
Epoch : 25, Loss : 0.12787893414497375

In [40]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.5371